# Generated by Django 2.2 on 2020-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estadoactividades_programa_proyecto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='programas'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='proyectos'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='siglas',
            field=models.CharField(max_length=15),
        ),
    ]
