# Generated by Django 2.2 on 2020-04-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200425_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectino',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='proyectinos'),
        ),
    ]
